COCCOC_VERSION = '77.0.3865.142'
OMAHA_VERSION = '2.5.15.106'
EXTENSION_VERSION_DICTIONARY = '1.3.6'
EXTENSION_VERSION_SAVIOR = '0.27.4'
EXTENSION_VERSION_RUNGRINH = '1.5.0.9'
EXTENSION_VERSION_AD_BLOCK_PLUS = '1.0.9'
USER_DATA_DIR = 'C:\\Users\\cuongld\\AppData\\Local\\CocCoc\\Browser\\User Data'
HOST_FILE = r'C:\Windows\System32\drivers\etc'

